### ISSUE TITLE
Effective 1.19.2 for Forge crashing on Minecraft 1.19.4, on the latest version of Forge.

### ISSUE THREAD

**Issue by TremendousTourmaline** [bottomtextdanny/Effective-Forge-#30]
In case it helps, here is the list of other mods that I am using:
- Appleskin 1.19.4
- WorldEdit 1.19.4
- CreativeCore for Forge 1.19.4
- Xaero's World Map 1.19.4
- Xaero's Minimap 1.19.4
- Iceberg 1.19.4
- Falling Leaves for Forge 1.19.4
- Sound Physics Remastered 1.19.4
- Advancement Plaques 1.19.4
- Ambient Sounds 1.19.4
- Visuality: Reforged 1.19.4
- Not Enough Animations for Forge 1.19.4
- Eating Animations for Forge 1.19.4
- Architectury 1.19.4
- Optifine 1.19.4 U I4

Here is the crash report:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-05-15 17:54:08
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.0.63-universal.jar%23212!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.0.63-universal.jar%23212!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:577) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:582) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:571) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:196) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1363) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1148) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:719) ~[client-1.19.4-20230314.122934-srg.jar%23207!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.63.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.63.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?] {}
-- MOD effective_fg --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.63.jar%23209!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.63.jar%23208!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/TextureStitchEvent$Pre
		at bottomtextdanny.effective_fg.particle_manager.ParticleStitcher.<init>(ParticleStitcher.java:15) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:classloading}
		at bottomtextdanny.effective_fg.EffectiveFg.setupClient(EffectiveFg.java:40) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:mixin,re:classloading}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.4-45.0.63.jar%23208!/:?] {}
		at bottomtextdanny.effective_fg.EffectiveFg.<init>(EffectiveFg.java:33) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:mixin,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.63.jar%23209!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.63.jar%23208!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /Users/gabriel/Library/Application Support/minecraft/mods/effective_fg-1.3.4.jar
	Failure message: Effective (Forge) (effective_fg) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.3.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.TextureStitchEvent$Pre
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.6.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at bottomtextdanny.effective_fg.particle_manager.ParticleStitcher.<init>(ParticleStitcher.java:15) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:classloading}
	at bottomtextdanny.effective_fg.EffectiveFg.setupClient(EffectiveFg.java:40) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:mixin,re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.4-45.0.63.jar%23208!/:?] {}
	at bottomtextdanny.effective_fg.EffectiveFg.<init>(EffectiveFg.java:33) ~[effective_fg-1.3.4.jar%23189!/:1.3] {re:mixin,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.4-45.0.63.jar%23209!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.4-45.0.63.jar%23208!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Mac OS X (aarch64) version 13.3.1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 341519224 bytes (325 MiB) / 973078528 bytes (928 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 10240.00
	Virtual memory used (MB): 6478.02
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 354.50
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230408-043701
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.2.02.zip
	OpenGlVersion: 4.1 Metal - 83.1
	OpenGlRenderer: Apple M1
	OpenGlVendor: Apple
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.63.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.63.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.63.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.63.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.63.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		gml@3.1.3
		javafml@null
		lowcodefml@null
		minecraft@1.0
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		AmbientSounds_FORGE_v5.2.18_mc1.19.4.jar          |Ambient Sounds                |ambientsounds                 |5.2.18              |COMMON_SET|Manifest: NOSIGNATURE
		mod-3.1.3.jar                                     |GroovyModLoader               |gml                           |3.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2+1.19.4.jar       |Player Animator               |playeranimator                |1.0.2+1.19.4        |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.12_mc1.19.4.jar          |CreativeCore                  |creativecore                  |2.10.12             |COMMON_SET|Manifest: NOSIGNATURE
		advancements_tracker_1.19.3-5.0.3.jar             |Advancements Tracker          |advancements_tracker          |5.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.3-mc1.19.4.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.3               |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.19.4-forge-1.1.9.jar                    |Iceberg                       |iceberg                       |1.1.9               |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.19.4-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.19.4-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.4.3_Forge_1.19.4.jar            |Xaero's Minimap               |xaerominimap                  |23.4.3              |COMMON_SET|Manifest: NOSIGNATURE
		Fallingleaves-1.19.4-2.1.0.jar                    |Falling Leaves                |fallingleaves                 |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		cgl-1.19.4-forge-0.2.5.jar                        |CommonGroovyLibrary           |commongroovylibrary           |0.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.30.2_Forge_1.19.4.jar            |Xaero's World Map             |xaeroworldmap                 |1.30.2              |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |COMMON_SET|Manifest: NOSIGNATURE
		effective_fg-1.3.4.jar                            |Effective (Forge)             |effective_fg                  |1.3.4               |ERROR     |Manifest: NOSIGNATURE
		AmbientEnvironment-forge-1.19.4-9.0.0.2.jar       |Ambient Environment           |ambientenvironment            |9.0.0.2             |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.14.jar                          |WorldEdit                     |worldedit                     |7.2.14+6360-094b734 |COMMON_SET|Manifest: NOSIGNATURE
		eatinganimation-1.19.4-4.2.0.jar                  |Eating Animation              |eatinganimation               |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-8.1.80-forge.jar                     |Architectury                  |architectury                  |8.1.80              |COMMON_SET|Manifest: NOSIGNATURE
		infinitemusic-1.7.0.jar                           |Infinite Music                |infinitemusic                 |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		visuality-forge-2.0+forge-mc1.19.3.jar            |Visuality: Reforged           |visuality                     |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.4-45.0.63-universal.jar                |Forge                         |forge                         |45.0.63             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19.4-2.4.3.jar                |AppleSkin                     |appleskin                     |2.4.3+mc1.19.4      |COMMON_SET|Manifest: NOSIGNATURE
		emotecraft-for-MC1.19.4-2.2.7-b.build.48-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.48    |COMMON_SET|Manifest: NOSIGNATURE
		AdvancementPlaques-1.19.4-1.4.9.jar               |Advancement Plaques           |advancementplaques            |1.4.9               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: db41dff6-29bb-4aff-a6b8-99cc25db1e80
	FML: 45.0
	Forge: net.minecraftforge:45.0.63

**Comment by Syclusion** [comment]
You should close this issue, its not for 1.19.4..... it is literally in the title. Mods aren't compatible across versions like that

**Comment by TremendousTourmaline** [comment]
Yeah, you're right. I'll close it.
